/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/uF6xBs50biv
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function About() {
  return (
    <div className="w-full -ml-24">
      <header className="py-8 px-4 md:px-6">
        <div className="container max-w-4xl text-left">
          <h1 className="text-2xl font-bold sm:text-3xl md:text-4xl">About Us</h1>
        </div>
      </header>
      <div className="container mx-auto max-w-4xl px-4 md:px-6 space-y-6">
        <div className="flex justify-start gap-4">
          <Link
            href="#"
            className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-6 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}
          >
            Get in touch
          </Link>
          <Link
            href="#"
            className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-6 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}
          >
            Visit a2sv.org
          </Link>
        </div>
        <div className="space-y-4 text-muted-foreground">
          <p>
          At Inxtract, we harness the power of AI to revolutionize the way research papers are consumed. Our mission is to make the process of digesting complex academic literature effortless and efficient. Through advanced AI summarization techniques, we distill dense research papers into concise, accessible summaries without compromising on depth or accuracy. Whether you're a student, researcher, or industry professional, Inxtract empowers you to stay ahead by providing clear, comprehensive insights from the latest studies. Join us in transforming the way knowledge is accessed and understood.
          </p>
          <p>
          We believe in the power of collaboration and strive to build strong partnerships with our clients. By
            understanding their unique challenges and needs, we are able to tailor our services to deliver customized
            solutions that drive tangible results.
          </p>
          <p>
          At Inxtract, we're committed to making research papers more accessible through innovative AI summarization techniques. By condensing intricate academic content into clear, informative summaries, we empower students, researchers, and professionals alike to grasp key insights swiftly and effectively. Join us in reshaping the landscape of knowledge discovery and utilization.
          </p>
        </div>
      </div>
      <div className="bg-muted py-12 px-4 md:px-6">
        <div className="container mx-auto max-w-4xl grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-6">
          <div className="flex flex-col items-center gap-3">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>MS</AvatarFallback>
            </Avatar>
            <div className="text-left">
              <div className="font-medium">Mohammed Shemim</div>
              <div className="flex items-center gap-1 text-muted-foreground">
                <GithubIcon className="w-4 h-4" />
                <a href="#" className="hover:underline">
                  mohammedshemim
                </a>
              </div>
            </div>
          </div>
          <div className="flex flex-col items-center gap-3">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>AK</AvatarFallback>
            </Avatar>
            <div className="text-left">
              <div className="font-medium">Amanuael Kebede</div>
              <div className="flex items-center gap-1 text-muted-foreground">
                <GithubIcon className="w-4 h-4" />
                <a href="#" className="hover:underline">
                  manuel-heav
                </a>
              </div>
            </div>
          </div>
          <div className="flex flex-col items-center gap-3">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>EM</AvatarFallback>
            </Avatar>
            <div className="text-left">
              <div className="font-medium">Eyouel Melkamu</div>
              <div className="flex items-center gap-1 text-muted-foreground">
                <GithubIcon className="w-4 h-4" />
                <a href="#" className="hover:underline">
                  Eyouel
                </a>
              </div>
            </div>
          </div>
          <div className="flex flex-col items-center gap-3">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>AS</AvatarFallback>
            </Avatar>
            <div className="text-left">
              <div className="font-medium">Abdulkerim Seid</div>
              <div className="flex items-center gap-1 text-muted-foreground">
                <GithubIcon className="w-4 h-4" />
                <a href="#" className="hover:underline">
                  abdulkerim
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function GithubIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
