/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4gSTstscXl8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function PlanSidebar() {
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle className="text-center">Your usage, current plan: Personal</CardTitle>
      </CardHeader>
      <CardContent className="flex flex-col items-center justify-center gap-4 py-8">
        <div className="text-5xl font-bold text-primary">68%</div>
        <div className="text-muted-foreground">of your monthly limit used</div>
      </CardContent>
      <CardFooter>
        <Button className="w-full">Upgrade plan</Button>
      </CardFooter>
    </Card>
  )
}
